// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VkMemesBackend.Models;

namespace VkMemesBackend.Migrations
{
    [DbContext(typeof(MemesDatabaseContext))]
    [Migration("20200715085834_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("VkMemesBackend.Models.MemeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Memes");
                });

            modelBuilder.Entity("VkMemesBackend.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemeModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemeModelId");

                    b.ToTable("TagModel");
                });

            modelBuilder.Entity("VkMemesBackend.Models.TagModel", b =>
                {
                    b.HasOne("VkMemesBackend.Models.MemeModel", null)
                        .WithMany("Tags")
                        .HasForeignKey("MemeModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
